# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Custom stuff
#

# Customize to your needs...
ARCH=`uname`

if [ $ARCH = "FreeBSD" ]; then
  export GOOS=freebsd
  export GOARCH=amd64
  export GOROOT=/usr/local/go
fi

if [ $ARCH = "Darwin" ]; then
  export EDITOR="/usr/local/bin/emacsclient"
  export VISUAL="${EDITOR} -nw"
  export ALTERNATE_EDITOR="/usr/local/bin/emacs"
  # Node.js
  export NODE_PATH="/usr/local/lib/node_modules"
  export NODE_BIN="/usr/local/share/npm/bin"
  export GOROOT=/usr/local/go
fi

if [ $ARCH = "Linux" ]; then
  export NODE_PATH="/usr/local/lib/node_modules"
  export NODE_BIN="/usr/share/npm/bin"
fi

export GOPATH=$HOME/libs/go
export GOBIN=$HOME/bin
export PATH=$HOME/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
export PATH=$PATH:/bin:/usr/games:$GOPATH/bin:$NODE_BIN

# Default editor unless not already set somewhere above OS specific
# Should do for BSD and Linux
if [ ! -n "$EDITOR" ]; then
  export EDITOR="emacsclient -t"
fi
if [ ! -n "$VISUAL" ]; then
  export VISUAL="emacsclient -t"
fi
if [ ! -n "$ALTERNATE_EDITOR" ]; then
  export ALTERNATE_EDITOR="emacs";
fi

if builtin type most &>/dev/null; then
  export PAGER="most -s"
fi

#
# Language
#

export LANG="en_US.UTF-8"
export LC_ALL=${LANG}

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath manpath path
typeset -gUT INFOPATH infopath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that info searches for manuals.
infopath=(
  /usr/local/share/info
  /usr/share/info
  $infopath
)

# Set the list of directories that man searches for manuals.
manpath=(
  /usr/local/share/man
  /usr/share/man
  $manpath
)

for path_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$path_file))
done
unset path_file

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

#
# Temporary Files
#

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi

# Local Variables:
# mode: sh
# End:
