# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
ARCH=`uname`

if [ $ARCH = "FreeBSD" ]; then
  port_search () {
    cd /usr/ports
    make search key=$1 | grep Path | awk '{print $2}'
    cd $OLDPWD
  }
fi

alias e="emacsclient -t"
alias ec="emacsclient -c"
alias tmux="ssh-agent tmux"

cook_and_clean() {
  bundle exec knife solo cook "$*" --no-chef-check
  bundle exec knife solo clean "$*"
}


alias git_left_over_local="git branch --merged master | grep -v 'master$' | \
                           xargs"
alias git_left_over_remote="git branch -r --merged origin/master | sed \
                              's/origin\\//:/' | egrep -v 'HEAD|master' | xargs"
alias todo="ag 'TODO((?!Prio).)*:'"
alias todo_for_me="ag 'TODO\s?(Flo2)?:'"
alias last_sha="git show | grep -e '^commit' | cut -f 2 -d \" \""

export TERM=xterm-256color

browse() { open $(eval ${1}) }
alias branch_current='git rev-parse --abbrev-ref HEAD'
alias branch_oldest_ancestor='/usr/bin/diff -u <(git rev-list --first-parent master) <(git rev-list --first-parent HEAD) | sed -ne "s/^ //p" | head -1'
alias branch_log='git log $(branch_oldest_ancestor)..HEAD'
alias branch_diff='git diff $(branch_oldest_ancestor)..HEAD'
alias branch_files='git diff $(branch_oldest_ancestor)..HEAD --diff-filter=ACMR --name-only --oneline'
alias bitbucket_repo_url='echo https://$(git remote -v | grep -oh "bitbucket.org[:/][^ ]\+.git" | head -1 | sed "s/:/\//" | sed "s/\.git$//")'
alias bitbucket_review_url='echo $(bitbucket_repo_url)/branches/compare/$(branch_current)..$(branch_oldest_ancestor)'
alias redmine_url='echo http://redmine.nwwo.de/issues/$(branch_current | grep -oh "^[0-9]\+")'
alias branch_rubocop='branch_files | grep  "\.\(rb\|gemspec\)$" | xargs rubocop'
alias bbb='browse bitbucket_repo_url'
alias bbbr='browse bitbucket_review_url'
alias bred='browse redmine_url'

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] &&\
  source $HOME/.tmuxinator/scripts/tmuxinator

[[ -s $HOME/.gvm/scripts/gvm ]] && \
  source $HOME/.gvm/scripts/gvm

#__rvm_project_rvmrc
# Local Variables:
# mode: sh
# End:
